local M = {entries={},paused=false,nextID=0}
local settingsKey = "desktoptoolkit.clipboard.v1"
function M.defaults()
    return {enabled=false,limit=50,minutes=30,excluded={"com.apple.Passwords","com.1password.1password","com.agilebits.onepassword7","com.bitwarden.desktop"}}
end
function M.validate(value)
    if type(value)~="table" or type(value.enabled)~="boolean" or type(value.limit)~="number" or value.limit%1~=0 or value.limit<10 or value.limit>100 or type(value.minutes)~="number" or value.minutes%1~=0 or value.minutes<1 or value.minutes>120 or type(value.excluded)~="table" then return nil,"容量须为 10–100 条，保留时间须为 1–120 分钟" end
    local config,seen={enabled=value.enabled,limit=value.limit,minutes=value.minutes,excluded={}},{}
    for _,id in ipairs(value.excluded) do
        if type(id)~="string" or not id:match("^[%w_%-]+%.[%w_.%-]+$") then return nil,"排除应用须填写有效 Bundle ID" end
        if not seen[id] then table.insert(config.excluded,id);seen[id]=true end
    end
    return config
end
function M.prune()
    local cutoff=hs.timer.secondsSinceEpoch()-M.config.minutes*60
    for i=#M.entries,1,-1 do if M.entries[i].time<=cutoff then table.remove(M.entries,i) end end
    while #M.entries>M.config.limit do table.remove(M.entries) end
end
local ignored={['org.nspasteboard.ConcealedType']=true,['org.nspasteboard.TransientType']=true,['org.nspasteboard.AutoGeneratedType']=true,['public.file-url']=true,['public.png']=true,['public.tiff']=true,['public.jpeg']=true}
function M.poll()
    M.prune()
    local count=hs.pasteboard.changeCount()
    if count==M.lastCount then return end
    M.lastCount=count
    if not M.config.enabled or M.paused then return end
    local application=hs.application.frontmostApplication()
    local bundle=application and application:bundleID()
    for _,id in ipairs(M.config.excluded) do if bundle==id then return end end
    for _,kind in ipairs(hs.pasteboard.contentTypes() or {}) do if ignored[kind] then return end end
    local value=hs.pasteboard.getContents()
    if type(value)~="string" or value=="" or #value>65536 then return end
    -- A copy occurring while reading must not be attributed to the earlier observation.
    if hs.pasteboard.changeCount()~=count then return end
    for i=#M.entries,1,-1 do if M.entries[i].text==value then table.remove(M.entries,i) end end
    M.nextID=M.nextID+1
    table.insert(M.entries,1,{id=M.nextID,text=value,time=hs.timer.secondsSinceEpoch()})
    M.prune()
end
function M.configure(config)
    if M.timer then M.timer:stop();M.timer=nil end
    M.config=config
    if config.enabled then
        M.lastCount=hs.pasteboard.changeCount() -- Never import the clipboard on enable/restart.
        M.prune()
        M.timer=hs.timer.doEvery(0.5,M.poll)
    else M.entries={};M.paused=false end
end
function M.save(value)
    local config,message=M.validate(value)
    if not config then return false,message end
    M.configure(config);hs.settings.set(settingsKey,config)
    return true,"剪贴板设置已保存"
end
function M.pause()
    if not M.config.enabled then return false,"请先启用剪贴板历史" end
    M.paused=not M.paused;M.lastCount=hs.pasteboard.changeCount()
    return true,M.paused and "已暂停记录" or "已恢复记录"
end
function M.copy(id)
    M.prune()
    for _,entry in ipairs(M.entries) do
        if entry.id==id then
            if not hs.pasteboard.setContents(entry.text) then return false,"复制失败" end
            M.lastCount=hs.pasteboard.changeCount()
            return true,"已复制，请在目标应用手动粘贴"
        end
    end
    return false,"记录已过期或被清除"
end
function M.clear() M.entries={};return true,"历史已清空" end
function M.snapshot()
    M.prune();return {config=M.config,paused=M.paused,entries=M.entries}
end
function M.menuItems()
    M.prune()
    local menu={
        {title=M.config.enabled and (M.paused and "已暂停记录" or "正在记录") or "历史记录未启用",disabled=true},
        {title="搜索历史 / 设置…",fn=M.openSettings},
        {title=M.paused and "恢复记录" or "暂停记录",disabled=not M.config.enabled,fn=function() M.pause() end},
        {title="-"},
    }
    for _,entry in ipairs(M.entries) do
        local text=entry.text:gsub("[\r\n\t]"," ")
        local length=utf8.len(text)
        if length and length>40 then text=text:sub(1,utf8.offset(text,41)-1).."…" end
        table.insert(menu,{title=text,fn=function() local ok,message=M.copy(entry.id);if not ok then hs.alert.show(message) end end})
    end
    if #M.entries==0 then table.insert(menu,{title="暂无历史",disabled=true}) end
    return menu
end
function M.start() M.configure(M.validate(hs.settings.get(settingsKey)) or M.defaults()) end
function M.startMenu(openSettings)
    M.openSettings=openSettings
    M.menu=hs.menubar.new():setTitle("📋"):setTooltip("DesktopToolkit 剪贴板历史")
    M.menu:setMenu(M.menuItems)
end
return M
