local M = {entries={},paused=false,nextID=0}
local settingsKey = "desktoptoolkit.clipboard.v1"
function M.defaults()
    return {enabled=false,limit=50,minutes=30,images=true,persistent=false,excluded={"com.apple.Passwords","com.1password.1password","com.agilebits.onepassword7","com.bitwarden.desktop"}}
end
function M.validate(value)
    if type(value)~="table" or type(value.enabled)~="boolean" or type(value.limit)~="number" or value.limit%1~=0 or value.limit<10 or value.limit>100 or type(value.minutes)~="number" or value.minutes%1~=0 or value.minutes<1 or value.minutes>120 or type(value.excluded)~="table" then return nil,"容量须为 10–100 条，保留时间须为 1–120 分钟" end
    if value.images~=nil and type(value.images)~="boolean" or value.persistent~=nil and type(value.persistent)~="boolean" then return nil,"图片和缓存设置格式无效" end
    local config,seen={enabled=value.enabled,limit=value.limit,minutes=value.minutes,images=value.images~=false,persistent=value.persistent==true,excluded={}},{}
    for _,id in ipairs(value.excluded) do
        if type(id)~="string" or not id:match("^[%w_%-]+%.[%w_.%-]+$") then return nil,"排除应用须填写有效 Bundle ID" end
        if not seen[id] then table.insert(config.excluded,id);seen[id]=true end
    end
    return config
end
local historyKey="desktoptoolkit.clipboard.history.v1"
local function directory() return hs.configdir.."/clipboard-history/" end
local function managed(path)
    return type(path)=="string" and path:sub(1,#directory())==directory() and path:sub(#directory()+1):match("^clip_%d+_%d+%.png$")
end
local function remove(entry)
    if managed(entry.path) then os.remove(entry.path);entry.path=nil end
end
local function ensureDirectory()
    local path=directory():sub(1,-2)
    local attr=hs.fs.symlinkAttributes(path)
    if attr then return attr.mode=="directory" end
    return hs.fs.mkdir(path)
end
function M.persist()
    if not M.config.persistent or not M.config.enabled then
        hs.settings.clear(historyKey)
        for _,entry in ipairs(M.entries) do remove(entry) end
        return true
    end
    local saved={}
    for _,entry in ipairs(M.entries) do
        if entry.kind=="image" then
            if not entry.path then
                local path=directory()..string.format("clip_%.0f_%d.png",entry.time*1000,entry.id)
                if not entry.image:saveToFile(path,true,"PNG") then return false,"图片缓存写入失败" end
                entry.path=path
            end
            table.insert(saved,{id=entry.id,kind="image",time=entry.time,path=entry.path})
        else table.insert(saved,{id=entry.id,kind="text",time=entry.time,text=entry.text}) end
    end
    hs.settings.set(historyKey,saved)
    return true
end
function M.prune()
    local changed=false
    local cutoff=hs.timer.secondsSinceEpoch()-M.config.minutes*60
    local imageCount,textCount=0,0
    for i=#M.entries,1,-1 do
        if M.entries[i].time<=cutoff then remove(M.entries[i]);table.remove(M.entries,i);changed=true end
    end
    local keep={}
    for _,entry in ipairs(M.entries) do
        if entry.kind=="image" then imageCount=imageCount+1 else textCount=textCount+1 end
        if entry.kind=="image" and imageCount>10 or entry.kind~="image" and textCount>M.config.limit then remove(entry);changed=true else table.insert(keep,entry) end
    end
    M.entries=keep
    if changed then M.persist() end
end
local function thumbnail(image)
    local size=image:size()
    local scale=math.min(1,120/math.max(size.w,size.h))
    return image:setSize({w=size.w*scale,h=size.h*scale})
end
function M.load()
    if not M.config.enabled or not M.config.persistent then return end
    local saved=hs.settings.get(historyKey)
    if type(saved)~="table" then return end
    M.entries={}
    for _,entry in ipairs(saved) do
        if type(entry)=="table" and type(entry.id)=="number" and entry.id>0 and entry.id%1==0 and type(entry.time)=="number" then
            local item
            if entry.kind=="text" and type(entry.text)=="string" and #entry.text<=65536 then item={id=entry.id,time=entry.time,kind="text",text=entry.text} end
            if entry.kind=="image" and managed(entry.path) then
                local attr=hs.fs.symlinkAttributes(entry.path)
                if attr and attr.mode=="file" and attr.size<=10485760 then
                    local image=hs.image.imageFromPath(entry.path)
                    if image then item={id=entry.id,time=entry.time,kind="image",image=image,path=entry.path,thumb=thumbnail(image),fingerprint=hs.hash.SHA256(image:encodeAsURLString(true,"PNG"))} end
                end
            end
            if item then M.nextID=math.max(M.nextID,item.id);table.insert(M.entries,item) end
        end
    end
    M.prune()
end
local ignored={['org.nspasteboard.ConcealedType']=true,['org.nspasteboard.TransientType']=true,['org.nspasteboard.AutoGeneratedType']=true,['public.file-url']=true}
function M.poll()
    M.prune()
    local count=hs.pasteboard.changeCount()
    if count==M.lastCount then return end
    M.lastCount=count
    if not M.config.enabled or M.paused then return end
    local application=hs.application.frontmostApplication()
    local bundle=application and application:bundleID()
    for _,id in ipairs(M.config.excluded) do if bundle==id then return end end
    for _,kind in ipairs(hs.pasteboard.contentTypes() or {}) do if ignored[kind] then return end end
    local image=M.config.images and hs.pasteboard.readImage() or nil
    local value,thumb,fingerprint
    if image then
        local size=image:size()
        if size.w<=0 or size.h<=0 or size.w*size.h>25000000 then return end
        local encoded=image:encodeAsURLString(true,"PNG")
        if not encoded or #encoded>13981070 then return end -- 10 MiB PNG, including base64 expansion.
        fingerprint=hs.hash.SHA256(encoded)
        thumb=thumbnail(image)
    else
        value=hs.pasteboard.getContents()
        if type(value)~="string" or value=="" or #value>65536 then return end
    end
    if hs.pasteboard.changeCount()~=count then return end
    for i=#M.entries,1,-1 do
        local entry=M.entries[i]
        if value and entry.text==value or fingerprint and entry.fingerprint==fingerprint then remove(entry);table.remove(M.entries,i) end
    end
    M.nextID=M.nextID+1
    table.insert(M.entries,1,{id=M.nextID,kind=image and "image" or "text",text=value,image=image,thumb=thumb,fingerprint=fingerprint,time=hs.timer.secondsSinceEpoch()})
    M.prune()
    local ok,message=M.persist();if not ok then hs.alert.show(message) end
end
function M.configure(config)
    if M.timer then M.timer:stop();M.timer=nil end
    M.config=config
    if config.enabled then
        M.lastCount=hs.pasteboard.changeCount() -- Never import the clipboard on enable/restart.
        M.prune()
        M.timer=hs.timer.doEvery(0.5,M.poll)
    else for _,entry in ipairs(M.entries) do remove(entry) end;M.entries={};M.paused=false end
end
function M.save(value)
    local config,message=M.validate(value)
    if not config then return false,message end
    if config.enabled and config.persistent and not ensureDirectory() then return false,"无法创建独立剪贴板缓存目录" end
    local old=M.config
    M.config=config
    local ok,errorMessage=M.persist()
    if not ok then M.config=old;return false,errorMessage end
    M.configure(config);hs.settings.set(settingsKey,config)
    return true,"剪贴板设置已保存"
end
function M.pause()
    if not M.config.enabled then return false,"请先启用剪贴板历史" end
    M.paused=not M.paused;M.lastCount=hs.pasteboard.changeCount()
    return true,M.paused and "已暂停记录" or "已恢复记录"
end
function M.copy(id,target)
    M.prune()
    for _,entry in ipairs(M.entries) do
        if entry.id==id then
            if target and not hs.accessibilityState() then return false,"直接粘贴需要 Nivlet 辅助功能权限" end
            local ok
            if entry.kind=="image" then ok=hs.pasteboard.writeObjects(entry.image) else ok=hs.pasteboard.setContents(entry.text) end
            if not ok then return false,"复制失败" end
            M.lastCount=hs.pasteboard.changeCount()
            if target then hs.timer.doAfter(0.15,function() if target:isRunning() then hs.eventtap.keyStroke({"cmd"},"v",0,target) end end) end
            return true,target and "已复制并请求粘贴" or "已复制，请在目标应用手动粘贴"
        end
    end
    return false,"记录已过期或被清除"
end
function M.clear() for _,entry in ipairs(M.entries) do remove(entry) end;M.entries={};M.persist();return true,"历史已清空" end
function M.preview(id)
    M.prune()
    for _,entry in ipairs(M.entries) do
        if entry.id==id and entry.kind=="image" then
            local url=entry.image:encodeAsURLString(true,"PNG")
            if not url or #url>13981070 then return nil,"图片无法预览或超出容量限制" end
            return {id=entry.id,time=entry.time,url=url}
        end
    end
    return nil,"图片已过期或被清除"
end
function M.snapshot()
    M.prune()
    local entries={}
    for _,entry in ipairs(M.entries) do
        table.insert(entries,{id=entry.id,kind=entry.kind,time=entry.time,text=entry.text or "图片",preview=entry.thumb and entry.thumb:encodeAsURLString(false,"PNG") or nil})
    end
    return {config=M.config,paused=M.paused,entries=entries}
end
function M.menuItems()
    M.prune()
    local target=hs.application.frontmostApplication()
    local menu={
        {title=M.config.enabled and (M.paused and "已暂停记录" or "正在记录") or "历史记录未启用",disabled=true},
        {title="搜索历史…",fn=function() M.openSettings("history") end},
        {title=M.paused and "恢复记录" or "暂停记录",disabled=not M.config.enabled,fn=function() M.pause() end},
        {title="-"},
    }
    for _,entry in ipairs(M.entries) do
        local text=(entry.text or "图片 "..os.date("%H:%M:%S",math.floor(entry.time))):gsub("[\r\n\t]"," ")
        local length=utf8.len(text)
        if length and length>40 then text=text:sub(1,utf8.offset(text,41)-1).."…" end
        table.insert(menu,{title=text,image=entry.thumb,fn=function(mods) local ok,message=M.copy(entry.id,mods and mods.alt and target or nil);if not ok then hs.alert.show(message) end end})
    end
    if #M.entries==0 then table.insert(menu,{title="暂无历史",disabled=true}) end
    table.insert(menu,{title="-"})
    table.insert(menu,{title="剪贴板设置…",fn=function() M.openSettings("settings") end})
    table.insert(menu,{title="清空历史…",disabled=#M.entries==0,fn=function()
        if hs.dialog.blockAlert("清空剪贴板历史？","仅移除此 App 的历史记录和缓存，不改系统当前剪贴板。","清空","取消","warning")=="清空" then M.clear() end
    end})
    return menu
end
function M.start()
    local config=M.validate(hs.settings.get(settingsKey)) or M.defaults()
    if config.enabled and config.persistent and not ensureDirectory() then config.persistent=false end
    M.configure(config);M.load()
end
function M.showPopup()
    if M.popup then M.popup:popupMenu(hs.mouse.absolutePosition()) end
end
function M.startMenu(openSettings)
    M.openSettings=openSettings
    M.menu=hs.menubar.new():setTitle("📋"):setTooltip("Nivlet 剪贴板历史")
    M.menu:setMenu(M.menuItems)
    M.popup=hs.menubar.new(false):setMenu(M.menuItems)
end
return M
